//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTable
    {
        public long RecId { get; set; }
        public string DeviceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long LogId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public Nullable<long> RefTempId { get; set; }
    
        public virtual Log Logs1 { get; set; }
        public virtual Log Log1 { get; set; }
    }
}
namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagram
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemperatureTable
    {
        public long Id { get; set; }
        public string Temperature { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<byte> FanStatus { get; set; }
    }
}
namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public long RecId { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
    }
}
namespace Database
{
    using System;
    
    public partial class sp_helpdiagramdefinition_Result
    {
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace Database
{
    using System;
    
    public partial class sp_helpdiagrams_Result
    {
        public string Database { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public string Owner { get; set; }
        public int OwnerID { get; set; }
    }
}
